import type { Response } from "express";
import PDFDocument from "pdfkit";

const CURRENCY_SYMBOLS: Record<string, string> = {
  PHP: "PHP ",
  USD: "USD ",
  EUR: "EUR ",
  GBP: "GBP ",
  JPY: "JPY ",
  KRW: "KRW ",
  SGD: "SGD ",
  AUD: "AUD ",
};

export type BookingEreceiptPayload = {
  bookingRef: string;
  guestName: string | null;
  guestEmail: string | null;
  hotelName: string;
  hotelAddress: string | null;
  roomName: string;
  roomType: string | null;
  bookingType: string;
  checkIn: string;
  checkOut: string;
  totalAmountLabel: string;
  paymentMethod: string;
  bookingStatus: string;
  paymentStatus: string;
  issuedAtLabel: string;
};

function paymentMethodLabel(method: string | null | undefined): string {
  const m = (method ?? "").toLowerCase();
  if (m === "online") return "Online / bank transfer";
  if (m === "cash") return "Cash (at property)";
  return method?.trim() || "—";
}

/** Build display strings before calling pipe. */
export function formatReceiptLabels(
  checkInIso: string,
  checkOutIso: string,
  issuedIso: string
): { checkIn: string; checkOut: string; issuedAtLabel: string } {
  const opts: Intl.DateTimeFormatOptions = {
    month: "long",
    day: "numeric",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  };
  return {
    checkIn: new Date(checkInIso).toLocaleString("en-US", opts),
    checkOut: new Date(checkOutIso).toLocaleString("en-US", opts),
    issuedAtLabel: new Date(issuedIso).toLocaleString("en-US", opts),
  };
}

export function formatReceiptAmount(
  totalAmount: string | number,
  currencyCode: string | null | undefined
): string {
  const code = (currencyCode ?? "PHP").toUpperCase();
  const prefix = CURRENCY_SYMBOLS[code] ?? `${code} `;
  const n = typeof totalAmount === "number" ? totalAmount : parseFloat(String(totalAmount));
  const num = Number.isFinite(n)
    ? n.toLocaleString("en-PH", { minimumFractionDigits: 2, maximumFractionDigits: 2 })
    : String(totalAmount);
  return `${prefix}${num}`;
}

export { paymentMethodLabel };

/**
 * Stream a Marble Stay e-receipt PDF to the HTTP response.
 */
export function pipeBookingEreceiptPdf(res: Response, data: BookingEreceiptPayload): void {
  const safeRef = data.bookingRef.replace(/[^\w-]/g, "");
  res.setHeader("Content-Type", "application/pdf");
  res.setHeader(
    "Content-Disposition",
    `attachment; filename="MarbleStay-e-receipt-${safeRef || "booking"}.pdf"`
  );

  const doc = new PDFDocument({ size: "LETTER", margin: 56 });
  doc.pipe(res);

  const navy = "#0F172A";
  const slate = "#334155";
  const muted = "#64748B";

  doc.fillColor(navy).fontSize(22).text("Marble Stay", { align: "center" });
  doc.moveDown(0.25);
  doc.fillColor(muted).fontSize(11).text("Official e-receipt (paid booking)", { align: "center" });
  doc.moveDown(1.25);

  doc.fillColor(slate).fontSize(10);
  doc.text(`Booking reference: ${data.bookingRef}`);
  doc.text(`Date issued: ${data.issuedAtLabel}`);
  doc.moveDown(0.75);

  doc.fillColor(navy).fontSize(12).text("Guest", { underline: true });
  doc.moveDown(0.2);
  doc.fillColor(slate).fontSize(10);
  doc.text(data.guestName?.trim() || "—");
  doc.text(data.guestEmail?.trim() || "—");
  doc.moveDown(0.75);

  doc.fillColor(navy).fontSize(12).text("Stay details", { underline: true });
  doc.moveDown(0.2);
  doc.fillColor(slate).fontSize(10);
  doc.text(`Property: ${data.hotelName}`);
  if (data.hotelAddress?.trim()) {
    doc.text(`Address: ${data.hotelAddress.trim()}`);
  }
  doc.text(`Room: ${data.roomName}`);
  if (data.roomType?.trim()) {
    doc.text(`Room type: ${data.roomType.trim()}`);
  }
  doc.text(`Stay type: ${data.bookingType}`);
  doc.text(`Check-in: ${data.checkIn}`);
  doc.text(`Check-out: ${data.checkOut}`);
  doc.moveDown(0.75);

  doc.fillColor(navy).fontSize(12).text("Payment", { underline: true });
  doc.moveDown(0.2);
  doc.fillColor(slate).fontSize(10);
  doc.text(`Amount paid: ${data.totalAmountLabel}`);
  doc.text(`Payment method: ${data.paymentMethod}`);
  doc.text(`Booking status: ${data.bookingStatus}`);
  doc.text(`Payment status: ${data.paymentStatus}`);
  doc.moveDown(1.25);

  doc.fillColor(muted).fontSize(8.5);
  doc.text(
    "This document was generated by Marble Stay for your records. For questions about your stay, contact the property or Marble Stay support.",
    { align: "left", lineGap: 2 }
  );

  doc.end();
}
