/** Country/region options for guest profile and signup (value === label). */
export const GUEST_COUNTRY_OPTIONS = [
    { value: "", label: "Select country / region" },
    { value: "Philippines", label: "Philippines" },
    { value: "United States", label: "United States" },
    { value: "United Kingdom", label: "United Kingdom" },
    { value: "Canada", label: "Canada" },
    { value: "Australia", label: "Australia" },
    { value: "Japan", label: "Japan" },
    { value: "Singapore", label: "Singapore" },
    { value: "South Korea", label: "South Korea" },
    { value: "China", label: "China" },
    { value: "India", label: "India" },
    { value: "Germany", label: "Germany" },
    { value: "France", label: "France" },
    { value: "Italy", label: "Italy" },
    { value: "Spain", label: "Spain" },
    { value: "Netherlands", label: "Netherlands" },
    { value: "United Arab Emirates", label: "United Arab Emirates" },
    { value: "Saudi Arabia", label: "Saudi Arabia" },
    { value: "Thailand", label: "Thailand" },
    { value: "Vietnam", label: "Vietnam" },
    { value: "Indonesia", label: "Indonesia" },
    { value: "Malaysia", label: "Malaysia" },
    { value: "New Zealand", label: "New Zealand" },
    { value: "Mexico", label: "Mexico" },
    { value: "Brazil", label: "Brazil" },
    { value: "Other", label: "Other" }
] as const;
